version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: navi-akash-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
      - ./generatedImages:/app/generatedImages:rw
    healthcheck:
      test: ["CMD", "bun", "run", "healthcheck.ts"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
    security_opt:
      - no-new-privileges:true
    # Uncomment for production if you want to use a specific network
    # networks:
    #   - navi-network

# Uncomment for production if you want to use a specific network
# networks:
#   navi-network:
#     driver: bridge 