version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: navi-akash-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./generatedImages:/app/generatedImages
    healthcheck:
      test: ["CMD", "bun", "-e", "process.exit(process.exitCode)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1' 