services:
  - type: web
    name: navi-akash-bot
    env: node
    plan: free
    buildCommand: bun run install:all && bun run build:all
    startCommand: bun start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BUNS_ENV  
        value: production
    autoDeploy: true
    region: oregon
    healthCheckPath: /api/health
